spring.application.name=cinema_app
# --- ?????? ---
server.port=8080

# --- ???? ?????? ---
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT ---
jwt.secret=MySuperSecretKeyForJWTGeneration12345
jwt.expiration-ms=3600000

# --- Refresh Token ---
refresh-token.expiration-ms=2592000000

# --- ???? ---
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
